# Generated by Django 5.2.3 on 2025-06-30 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupdocument',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='startup',
            name='tags',
            field=models.ManyToManyField(blank=True, to='startups.tag'),
        ),
    ]
