# Generated by Django 5.2.3 on 2025-06-30 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('interested_in_tags', models.ManyToManyField(blank=True, related_name='investors', to='startups.tag')),
                ('liked_startups', models.ManyToManyField(blank=True, related_name='liked_by_investors', to='startups.startup')),
            ],
        ),
    ]
