# Generated by Django 5.2.3 on 2025-07-01 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
        ('startups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorprofile',
            name='liked_startups',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='investors.investorprofile')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='startups.startup')),
            ],
            options={
                'unique_together': {('investor', 'startup')},
            },
        ),
    ]
